/IronFilter/det/setFilterCellSpacing 76.0 cm
/IronFilter/det/setPolyHeight 30.0 cm
/IronFilter/det/setMultiplierLeadHeightFront 15.0 cm
/IronFilter/det/setModeratorAluminumHeight 30 cm
/IronFilter/det/setModeratorTitaniumHeight 5.0 cm # to get the DT position add the number till here
/IronFilter/det/setMultiplierLeadHeightRear 20.0 cm
/IronFilter/det/setMultiplierLeadRadius 20.0 cm
/IronFilter/det/setModeratorAluminumRadius 15.0 cm
/IronFilter/det/setModeratorTitaniumRadius 15.0 cm
/IronFilter/det/setTestX 0 m
/IronFilter/det/setTestY 0 m
/IronFilter/det/setTestZ 0 m

/run/initialize
/tracking/verbose 0

/random/setSeeds 1233 4388

/process/list
/run/printProgress 1000

# Set the file name
/filename/setFilename Example.root

/gps/particle neutron

#/gps/energy 14.1 MeV
/gps/energy 0.024 MeV

#/gps/position 0 0 100.0 cm
#/gps/position 35 0 -50 cm
/gps/position 0 12 0 cm

#/gps/position 0 156 0 cm
/gps/direction 0 -1 0
#/gps/direction 0 1 0
#/gps/ang/type iso


#/analysis/setFileName testgeantino
/run/beamOn 100000
